/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _HELLOCL_H_
#define _HELLOCL_H_
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jstring JNICALL Java_org_code_testopencl_MainActivity_testOCL
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
